services:
  - type: web
    name: storyup-app
    env: node
    buildCommand: |
      cd frontend && npm install
      cd ../backend && npm install
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    plan: free
    autoDeploy: true
