services:
  - type: web
    name: storyup-app
    env: node
    buildCommand: |
      cd frontend && npm install && npm run build
      cd .. && npm install
    startCommand: node backend/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    plan: free
    autoDeploy: true
